### ISSUE TITLE
singly-linked-list 1.4.1 not supported

### ISSUE THREAD

**Issue by Kidrik** [jasonsjones/simple-hashtable#11]
Hello,
Simple-hashtable has singly-linked-list dependency as ^1.4.0 but now singly-linked-list has a 1.4.1 version(And simple-hashtable is accepting that can work with this version as you see)   but library is returning an error saying: 
node_modules/simple-hashtable/index.js:161
            this.table[index] = new LinkedList();
                                ^
TypeError: LinkedList is not a constructor

I believe you should review dependencies or update simple-hashtable version to support singly-linked-list 1.4.1

Thank you!

Rgrds,

Juan

**Comment by jasonsjones** [comment]
Hi @Kidrik, apologies for the delayed response, but thank you for filing this issue.  I'll will certainly take a look.  I _think_ I may know what the problem is and hope to publish a fix today.

**Comment by Kidrik** [comment]
> Hi @Kidrik, apologies for the delayed response, but thank you for filing this issue. I'll will certainly take a look. I _think_ I may know what the problem is and hope to publish a fix today.

Nice! Thank you!
